### ISSUE TITLE
Approved列をshow_status列に変更

### ISSUE THREAD

**Issue by kilisima** [tatsuaki-suzuki/mma_jp#3]
Approved列をshow_status列に変更

| show_status | 説明 |
|--|--|
| 0 |非表示|
|1|日付あり表示|
|2|日付未定表示|

**Comment by tatsuaki-suzuki** [comment]
一応、日付未定のやつは、2099にしたのですが、それで大丈夫ですかね？
制御はshow_statusだと思いますが。

**Comment by kilisima** [comment]
未定のやつは未定って入れてもらえれば！

**Comment by tatsuaki-suzuki** [comment]
そこ聞こうと思ってました。dateに未定だとエラーでちゃいますね。
これシートへ書く文字コードが間違ってるのかな・・・

----
        if(index === 3) {
          if(String(item) === "未定") {

**Comment by kilisima** [comment]
ごめんなさい、アプリ側の問題だったので、アプリ側に修正いれました！

**Comment by tatsuaki-suzuki** [comment]
ありがとうございました！
大丈夫そうです。
今週こそ、一旦クローズリリースできそうです！！！
