### ISSUE TITLE
BottomNavigationBarの表示処理を追加

### ISSUE THREAD

**Issue by kilisima** [tatsuaki-suzuki/mma_jp#4]
BottomNavigationBarのクリック処理を追加
リストの表示を変える

- 最近の試合 \
未定含む未来を表示
- 過去の試合 \
過去の日付のデータを表示
- 試合の連絡 \
Google Formを表示（遷移処理はそのまま使う）

**Comment by tatsuaki-suzuki** [comment]
・最近の試合
未定含む未来を表示
・過去の試合
過去の日付のデータを表示
・試合の連絡
Google Formを表示（遷移処理はそのまま使う）
・このサイトについて
このサイトの説明をポップアップからこちらに移動

**Comment by tatsuaki-suzuki** [comment]
４カラムにする

**Comment by tatsuaki-suzuki** [comment]
右上はメールボタンにする

**Comment by kilisima** [comment]
完了
